// 0 - Dusuk
// 1 - Orta
// 2 - Yuksek
// 3 - Cok yuksek

// 1 Mart 2021 de aciklanan yasaklarla belirlenene harita
// risk degerleri.

const cities = {
        "ADANA": 1,
        "ADIYAMAN": 3,
        "AFYONKARAHİSAR": 1,
        "AĞRI": 0,
        "AMASYA": 3,
        "ANKARA": 1,
        "ANTALYA": 2,
        "ARTVİN": 2,
        "AYDIN": 1,
        "BALIKESİR": 3,
        "BİLECİK": 2,
        "BİNGÖL": 0,
        "BİTLİS": 0,
        "BOLU": 2,
        "BURDUR": 3,
        "BURSA": 1,
        "ÇANAKKALE": 2,
        "ÇANKIRI": 1,
        "ÇORUM": 1,
        "DENİZLİ": 1,
        "DİYARBAKIR": 0,
        "EDİRNE": 3,
        "ELAZIĞ": 1,
        "ERZİNCAN": 1,
        "ERZURUM": 1,
        "ESKİŞEHİR": 1,
        "GAZİANTEP": 1,
        "GİRESUN": 3,
        "GÜMÜŞHANE": 3,
        "HAKKARİ": 0,
        "HATAY": 1,
        "ISPARTA": 1,
        "MERSİN": 2,
        "İSTANBUL": 2,
        "İZMİR": 2,
        "KARS": 1,
        "KASTAMONU": 1,
        "KAYSERİ": 2,
        "KIRKLARELİ": 2,
        "KIRŞEHİR": 1,
        "KOCAELİ": 2,
        "KONYA": 3,
        "KÜTAHYA": 2,
        "MALATYA": 1,
        "MANİSA": 1,
        "KAHRAMANMARAŞ": 1,
        "MARDİN": 0,
        "MUĞLA": 2,
        "MUŞ": 0,
        "NEVŞEHİR": 1,
        "NİĞDE": 2,
        "ORDU": 3,
        "RİZE": 3,
        "SAKARYA": 3,
        "SAMSUN": 3,
        "SİİRT": 0,
        "SİNOP": 3,
        "SİVAS": 1,
        "TEKİRDAĞ": 2,
        "TOKAT": 3,
        "TRABZON": 3,
        "TUNCELİ": 1,
        "ŞANLIURFA": 0,
        "UŞAK": 0,
        "VAN": 0,
        "YOZGAT": 1,
        "ZONGULDAK": 2,
        "AKSARAY": 3,
        "BAYBURT": 1,
        "KARAMAN": 2,
        "KIRIKKALE": 2,
        "BATMAN": 0,
        "ŞIRNAK": 0,
        "BARTIN": 1,
        "ARDAHAN": 2,
        "IĞDIR": 0,
        "YALOVA": 2,
        "KARABÜK": 1,
        "KİLİS": 2,
        "OSMANİYE": 3,
        "DÜZCE": 2,
}


export default cities;